### ISSUE TITLE
Ui related Issues

### ISSUE THREAD

**Issue by pras75299** [pesto-students/Snake-Snacks#11]
[Loom video](https://www.loom.com/share/00ba24c70a9540c4b2e8e07cad1d5ecb)
1- When you are watching the video, In the top right corner, there is a background behind the cross button, which is translucent, I'm not sure you are planning to keep it or not.
2- The cross button outline seems broken while clicking
3- When the snake is moving, there is a border following it, it didn't get captured in the video, please check image
4- For food image you should use SVG instead of png
![2](https://user-images.githubusercontent.com/24312991/101920310-a5380080-3bf1-11eb-93a8-0184bff61602.png)
![Screenshot 2020-12-10 212343](https://user-images.githubusercontent.com/24312991/101920324-a9641e00-3bf1-11eb-9565-cf7b24368fa2.png)

@ArfatSalman @durgakiran

**Comment by durgakiran** [comment]
resolved with #13
